### ISSUE TITLE
Client->logout not clearing session

### ISSUE THREAD

**Issue by jadissa** [Jasig/phpCAS#95] opened 2013-09-30 16:03 UTC
I looked into this and found the function phpCAS::logout(); does not close the session out of the box.

Currently, it has:
        session_write_close();
        header('Location: '.$cas_url);
        phpCAS::trace("Prepare redirect to : ".$cas_url);

```
    session_unset();
    session_destroy();
```

And should be:
        session_unset();
        session_destroy();
        session_write_close();
        header('Location: '.$cas_url);
        phpCAS::trace("Prepare redirect to : ".$cas_url);

Notice the original writes out the session end before it unsets or destroys its properties. Additionally and even more alarmingly is that it redirects users before it can ever destroy the session.

**Comment by porcospino** [comment] 2015-07-21 14:01
9d8b7c7 looks to be incomplete.  The client is still redirected before the session is unset or destroyed.  fbc87b5 might fix it properly.

**Comment by mashimaroa15** [comment] 2015-11-30 15:22
I'm finding this is still not fixed in  1.3.3+ ?? The session is still not cleared after the redirection to server CAS

**Comment by jfritschi** [comment] 2015-11-30 18:59
Have you tried 1.3.4 or the current master? Please retest with latest version.

Please also share the relevant debug log. (PM or mail if you want) Please also share info how to reproduce (Browser etc.) and maybe the test cases you have used.

I'm happy to debug this but need a bit more info.

**Comment by jadissa** [comment] 2015-12-11 01:08
It's funny to me that this is still a thing...

**Comment by jfritschi** [comment] 2015-12-13 08:11
You know what is really funny: People using open source software and being lazy. Dropping rude one-liners and not contributing.

I have verified multiple times (e.g. example_simple.php) that the logout code works. I have now added even more debug info to the log. 

phpcas has wonderful debug logs to debug issues like this. I have not received a single one regarding this supposed still existing bug. I have not received a single example code to reproduce. I cannot reproduce this bug but I can even demonstrate in a vanilla setup that it works as designed.

I will not chase a needle in a haystack that is most likely related to your particular integration, setup or even bogus.

Stop complaining and start contributing!

I'm reopening this issue for the time being. Maybe someone will actually contribute.

**Comment by messinadm** [comment] 2015-12-30 21:20
I think i'm encountering this on example_simple.php. I've turned on the cas_debug and have the trace. I grabbed the latest phpcas with composer for another project, but manually moved it over for this test.

It looks to me as something goes wrong when the cas server posts after the logout url is hit. I'm new to this, so apologize if this is off topic.

[CAS Debugging.pdf](https://github.com/Jasig/phpCAS/files/75192/CAS.Debugging.pdf)

**Comment by messinadm** [comment] 2016-01-08 01:06
Can someone help me understand how the example_simple.php is supposed to know how to remove the session when it receives the POST with the logoutRequest info? 

Is my CAS server failing to include the php session cookie established by the client? I don't see it in the HTTP reqeust sent from our CAS server. It looks to me as if the POST request is treated as any other unauthenticated request and simply redirected to CAS server to authenticate in the phpCAS::forceAuthentication() method.

**Comment by jadissa** [comment] 2016-01-08 23:42
This conversation is ridiculous. I'm out. It takes like 5 loc to fix this... like 10 seconds of coding... it could have been done the moment I supplied working code. Good luck to you. lmfao

**Comment by messinadm** [comment] 2016-01-09 00:48
Sorry to see you go. I understand enough about the code now to ask a few more questions.

Directly calling the logout function from code on 1.3.4 from the code DOES clear the session for our code. Here's the logs demonstrating it.
[CAS Logout.pdf](https://github.com/Jasig/phpCAS/files/83460/CAS.Logout.pdf)

However. hitting the CAS server logout page from a browser instead, DOES NOT clear the session. The logout POST request seems to be incorrectly sending a 301 response instead of invoking the logout method.

So here are my questions:
1) Should I be discussing this in a new issue?
2) How is the logout message sent from the CAS server to my page as a POST with the logout xml supposed to invoke a logout to clear the session? Should my CAS server be including a session cookie?

**Comment by jfritschi** [comment] 2016-01-09 11:51
@messinadm Thank you for the debug logs.

The 2nd log shows that the logout works as designed. If you would be running the current development version "master" or "dev-master" on composer you would get even debug information on the session termination since I added a bit more debug info since 1.3.4 to make sure the session is terminated. 

I think your first debug log shows that you do not have a proper "SingleSignOut" setup. Hitting the logout page on the CAS server will never terminate a session on any website that has been casified with a CAS client application unless this advanced feature has been properly configured on both ends. This code on the client side is not part of the "simple" example but in the advanced and logout examples. https://github.com/Jasig/phpCAS/blob/master/docs/examples/example_advanced_saml11.php
https://github.com/Jasig/phpCAS/blob/master/docs/examples/example_logout.php

Documentation on this complicated feature "SingleSignOut/SingleLogOut" can be found on the wiki:
https://wiki.jasig.org/display/casc/phpcas+examples#phpCASexamples-HandlelogoutrequestsfromtheCASserver

Please be aware that this is for good reason (e.g security) but also since the feature very non-intuitive for the end user. Just consider a user clicking "Logout" on application A while having an open session B with unsaved data. If you do not implement proper local (one application) and federation wide logout (all applications) procedures the user will loose all his data on B and doesn't know/understand why. This is why in default the logout call to a CAS server will only prevent you to authenticaticate any new application. Any existing local session will work until they expire, SingleLogout is implemented or you force some kind of regular "renewal" of a local session.

The most important technical requirement for a logout request directly to the CAS server to terminate local CAS client sessions is the following:
* Your service (URL submitted to the CAS server as service) needs to be SSL
* The SSL Cert on this URL must be trusted and valid from the perspective of the CAS server! (with the java trust store/settings of the CAS server)
* The URL of your service must be reachable from the CAS server (beware of firewalls/reverse proxy/loadbalancer setups)
* The CAS client must be able to read an incoming logout call from the CAS server (see examples above)
* You must be using the stock session cookie concept from phpCAS or implement you own handlers to fit your custom setup (can be done via setSingleSignoutCallback()) to hook your code into the phpCAS logic.

This all is due to the fact that the CAS server uses an overall "CAS community session" and the clients initiate their own local CAS client session. If you hit the CAS server logout page the CAS server needs to securely inform all CAS clients to terminate their local sessions.

@jadissa The code you supplied was over 2 years ago and multiple commits have been done so far. Those commits fixed a bug that was existing. You now claim there is still a bug but do not supply any  evidence or concrete steps to reproduce. If have added more debug code that very clearly highlights the working functionality of the logout function in the debug logs.

I can only speculate about your reasons but there are several things you might be overlooking:
* php execution continues after a "Location" redirect, which means that the order is pretty much irrelevant to session invalidation (as can be seen from the debug logs) 
* The session is always terminated on the server side only. No cookie is removed on the client side. Thats how php works. The existence of the session cookie is not a proof that a session still exists.
* You could manually resend the cookie with an expired date but this is not possible during a "Location" redirect. It's a know bug/feature. 

This overall setup leads to one odd behavior that is however functionality wise not a problem. After logout the client may return with a still valid (based on time) Session ID cookie and phpCAS will restore an _empty_ and _not authenticated_ session that has the name "ST-XXX...." which on brief inspection looks like the user is still logged in. This is however not the case.
I have added some debug code that highlight this and shows that the right code path is taken. For this odd cookie ID behavior I don't see any non-intrusive way to fix it. Any fix would involve renaming cookies which is always tricky and may trigger other bugs.

_As always I'm really open to fixing bug but please submit substantiated bug reports that I can reproduce/retrace the problem. I will not change code based on somebody claiming that some snippet fixes "something" when this issue is not obvious or reproduce able._

**Comment by phackwer** [comment] 2016-05-21 01:17
I disagree. White logging out usually means to destroy the session data, it's not a required feature for this lib. Althought it could, of course, be a parameter.

**Comment by phackwer** [comment] 2016-05-21 01:19
I meant "while". Cell phone typing

**Comment by jfritschi** [comment] 2017-02-27 20:30
Closing the issue after no further info for over a year

**Closed by jfritschi** 2017-02-27 20:30 UTC
Labels: Major Bug

**Comment by mzico** [comment] 2020-02-27 06:51
Just to share with you guys.... ( it's been couple of years old issue as I see ): 

My Gluu Server is configured for SLO ( Single Logout ) and it's happening properly for SAML apps + Gluu Server itself. But... for phpCAS .. it's not happening from CAS app side ( though... logging out happening from Gluu Server ). Here is the screencast: https://youtu.be/a6Y5w1VJesI

**Comment by phy25** [comment] 2020-02-27 06:58
@mzico Could you post debug logs so that someone can at least help you better?

**Comment by mzico** [comment] 2020-02-27 08:25
@phy25 : thanks! it's kinda hard ( or I am missing something ) get phpCAS.log file. I tried to follow [this](https://apereo.atlassian.net/wiki/spaces/CASC/pages/103252650/phpCAS+troubleshooting) but I don't see 'phpCAS.log' anywhere in my Ubuntu system. I'll try later on.

**Comment by jfritschi** [comment] 2020-02-28 20:55
The logs are most likely in a folder that is named something like:
> /tmp/systemd-private-[hash]-apache2.service

Ubuntu ist most likely using systemd tmp security settings:
https://www.maxoberberger.net/blog/2017/10/debian-9-private-tmp.html
